- set_fact: rvm_wrapper_command="cd {{current_path}} && ~/.rvm/bin/rvm ruby-{{ruby_version}}@{{ruby_gemset}} --create do"

- name: start unicorn
  shell: "{{ rvm_wrapper_command }} bash -lc 'bundle exec unicorn_rails -c config/unicorn.rb -E {{rails_env_name}} -D'"
