# To which hosts we want to apply this play
- hosts: all
  # Log in as user
  remote_user: '{{deploy_user_name}}'
  # Use sudo
  become: yes
  # Don't need to gather facts about the system
  gather_facts: no

  tasks:
    - include: ../tasks/apt.yml