- name: Add puma config
  template: src=roles/webserver/backend/templates/puma_production.j2 dest={{app_path}}/current/config/puma.rb force=yes mode=755

- name: Make shared/tmp/sockets
  file: path={{item}} state=directory
  with_items:
    - '{{app_path}}/shared/tmp/sockets'
    - '{{app_path}}/shared/tmp/pids'

- set_fact: rvm_wrapper_command="cd {{current_path}} && ~/.rvm/bin/rvm ruby-{{ruby_version}}@{{ruby_gemset}} --create do"

- name: check profile for secret_key
  shell: grep SECRET_KEY_BASE .profile
  register: profile_check
  ignore_errors: yes

- name: Create secret token
  shell: "{{ rvm_wrapper_command }} bash -lc 'echo -e \"export SECRET_KEY_BASE=`bundle exec rake secret`\" >> ~/.profile'"
  when: profile_check|failed

- name: stop puma
  shell: "kill -9 `cat {{shared_path}}/tmp/pids/puma.pid`"
  ignore_errors: yes

- name: start puma
  shell: "{{ rvm_wrapper_command }} bash -lc 'bundle exec puma -C config/puma.rb -e {{rails_env_name}} -d'"
